-- MySQL Script generated by MySQL Workbench
-- Mon Mar 27 09:16:30 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Originale
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Originale
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Originale` DEFAULT CHARACTER SET utf8 ;
USE `Originale` ;

-- -----------------------------------------------------
-- Table `Originale`.`Specialiter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Originale`.`Specialiter` (
  `id_Specialiter` INT NOT NULL,
  `nom_Specialiter` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Specialiter`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Originale`.`Etudiant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Originale`.`Etudiant` (
  `id_Etudiant` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `mot-de-passe` VARCHAR(45) NOT NULL,
  `id_Specialiter` INT NOT NULL,
  `Specialiter_id_Specialiter` INT NOT NULL,
  PRIMARY KEY (`id_Etudiant`),
  CONSTRAINT `fk_Etudiant_Specialiter1`
    FOREIGN KEY (`Specialiter_id_Specialiter`)
    REFERENCES `Originale`.`Specialiter` (`id_Specialiter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Etudiant_Specialiter1_idx` ON `Originale`.`Etudiant` (`Specialiter_id_Specialiter` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Originale`.`Enseignant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Originale`.`Enseignant` (
  `id_Enseignant` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `mot_de_passe` VARCHAR(45) NOT NULL,
  `id_Specialiter` INT NULL,
  PRIMARY KEY (`id_Enseignant`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Originale`.`Note`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Originale`.`Note` (
  `id_Note` INT NOT NULL,
  `id_Etudiant` INT NULL,
  `id_Module` INT NULL,
  `note` FLOAT NULL,
  PRIMARY KEY (`id_Note`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Originale`.`Absence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Originale`.`Absence` (
  `id_Absence` INT NOT NULL,
  `id_Etudiant` INT NULL,
  `id_Enseignant` INT NULL,
  `date` DATE NOT NULL,
  `justification` VARCHAR(45) NULL,
  `Enseignant_id_Enseignant` INT NOT NULL,
  PRIMARY KEY (`id_Absence`),
  CONSTRAINT `fk_Absence_Enseignant1`
    FOREIGN KEY (`Enseignant_id_Enseignant`)
    REFERENCES `Originale`.`Enseignant` (`id_Enseignant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Absence_Enseignant1_idx` ON `Originale`.`Absence` (`Enseignant_id_Enseignant` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Originale`.`Module`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Originale`.`Module` (
  `id_Module` INT NOT NULL,
  `id_Specialiter` INT NULL,
  `nom_module` VARCHAR(45) NOT NULL,
  `coefficient` FLOAT NOT NULL,
  PRIMARY KEY (`id_Module`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Originale`.`Etudiant_Absence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Originale`.`Etudiant_Absence` (
  `Etudiant_id_Etudiant` INT NOT NULL,
  `Absence_id_Absence` INT NOT NULL,
  PRIMARY KEY (`Etudiant_id_Etudiant`, `Absence_id_Absence`),
  CONSTRAINT `fk_Etudiant_has_Absence_Etudiant`
    FOREIGN KEY (`Etudiant_id_Etudiant`)
    REFERENCES `Originale`.`Etudiant` (`id_Etudiant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Etudiant_has_Absence_Absence1`
    FOREIGN KEY (`Absence_id_Absence`)
    REFERENCES `Originale`.`Absence` (`id_Absence`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Etudiant_has_Absence_Absence1_idx` ON `Originale`.`Etudiant_Absence` (`Absence_id_Absence` ASC) VISIBLE;

CREATE INDEX `fk_Etudiant_has_Absence_Etudiant_idx` ON `Originale`.`Etudiant_Absence` (`Etudiant_id_Etudiant` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Originale`.`Etudiant_Note`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Originale`.`Etudiant_Note` (
  `Etudiant_id_Etudiant` INT NOT NULL,
  `Note_id_Note` INT NOT NULL,
  PRIMARY KEY (`Etudiant_id_Etudiant`, `Note_id_Note`),
  CONSTRAINT `fk_Etudiant_has_Note_Etudiant1`
    FOREIGN KEY (`Etudiant_id_Etudiant`)
    REFERENCES `Originale`.`Etudiant` (`id_Etudiant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Etudiant_has_Note_Note1`
    FOREIGN KEY (`Note_id_Note`)
    REFERENCES `Originale`.`Note` (`id_Note`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Etudiant_has_Note_Note1_idx` ON `Originale`.`Etudiant_Note` (`Note_id_Note` ASC) VISIBLE;

CREATE INDEX `fk_Etudiant_has_Note_Etudiant1_idx` ON `Originale`.`Etudiant_Note` (`Etudiant_id_Etudiant` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Originale`.`Module_Specialiter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Originale`.`Module_Specialiter` (
  `Module_id_Module` INT NOT NULL,
  `Specialiter_id_Specialiter` INT NOT NULL,
  PRIMARY KEY (`Module_id_Module`, `Specialiter_id_Specialiter`),
  CONSTRAINT `fk_Module_has_Specialiter_Module1`
    FOREIGN KEY (`Module_id_Module`)
    REFERENCES `Originale`.`Module` (`id_Module`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Module_has_Specialiter_Specialiter1`
    FOREIGN KEY (`Specialiter_id_Specialiter`)
    REFERENCES `Originale`.`Specialiter` (`id_Specialiter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Module_has_Specialiter_Specialiter1_idx` ON `Originale`.`Module_Specialiter` (`Specialiter_id_Specialiter` ASC) VISIBLE;

CREATE INDEX `fk_Module_has_Specialiter_Module1_idx` ON `Originale`.`Module_Specialiter` (`Module_id_Module` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Originale`.`Specialiter_Enseignant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Originale`.`Specialiter_Enseignant` (
  `Specialiter_id_Specialiter` INT NOT NULL,
  `Enseignant_id_Enseignant` INT NOT NULL,
  PRIMARY KEY (`Specialiter_id_Specialiter`, `Enseignant_id_Enseignant`),
  CONSTRAINT `fk_Specialiter_has_Enseignant_Specialiter1`
    FOREIGN KEY (`Specialiter_id_Specialiter`)
    REFERENCES `Originale`.`Specialiter` (`id_Specialiter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Specialiter_has_Enseignant_Enseignant1`
    FOREIGN KEY (`Enseignant_id_Enseignant`)
    REFERENCES `Originale`.`Enseignant` (`id_Enseignant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Specialiter_has_Enseignant_Enseignant1_idx` ON `Originale`.`Specialiter_Enseignant` (`Enseignant_id_Enseignant` ASC) VISIBLE;

CREATE INDEX `fk_Specialiter_has_Enseignant_Specialiter1_idx` ON `Originale`.`Specialiter_Enseignant` (`Specialiter_id_Specialiter` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Originale`.`Note_Module`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Originale`.`Note_Module` (
  `Note_id_Note` INT NOT NULL,
  `Module_id_Module` INT NOT NULL,
  PRIMARY KEY (`Note_id_Note`, `Module_id_Module`),
  CONSTRAINT `fk_Note_has_Module_Note1`
    FOREIGN KEY (`Note_id_Note`)
    REFERENCES `Originale`.`Note` (`id_Note`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Note_has_Module_Module1`
    FOREIGN KEY (`Module_id_Module`)
    REFERENCES `Originale`.`Module` (`id_Module`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Note_has_Module_Module1_idx` ON `Originale`.`Note_Module` (`Module_id_Module` ASC) VISIBLE;

CREATE INDEX `fk_Note_has_Module_Note1_idx` ON `Originale`.`Note_Module` (`Note_id_Note` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
